// import React from 'react'
import styles from "./pricing.module.css"


export const metadata = {
  title: "METADATA DEPUIS PRICING",
  description: "Generated by create next app",
  openGraph:{
    title:"Mon site",
    description: "Abcde"
  }
};

function page() {
    console.log(styles);
  return (
    <div>
      <h1 className={styles.title}>Pricing</h1>
    </div>
  )
}

export default page
